#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	ANNOUNCETIMERUISCRIPT,
	ATTACKRANGESCRIPT,
	BASICATTACKSCRIPT,
	BLUESCRIPT,
	BUSHSCRIPT,
	CAMERAMOVESCRIPT,
	CHAMPIONSCRIPT,
	CHARACTERUISCRIPT,
	COOLDOWNUISCRIPT,
	DRAGONHPUISCRIPT,
	DRAGONSCRIPT,
	EXPRATIOUISCRIPT,
	FONTUISCRIPT,
	GROMPSCRIPT,
	GROWSCALESCRIPT,
	HPMPRATIOUISCRIPT,
	INGAMECAMERASCRIPT,
	INHIBITORSCRIPT,
	INVENTORYUISCRIPT,
	JINXESCRIPT,
	JINXRSCRIPT,
	JINXSCRIPT,
	JINXWSCRIPT,
	JUNGLEMINIHPSCRIPT,
	JUNGLEMOBHPSCRIPT,
	JUNGLEMONSTERSCRIPT,
	KILLLOGUISCRIPT,
	KRUGMINISCRIPT,
	KRUGSCRIPT,
	MALPHITEBASICATTACKHITEFFECTSCRIPT,
	MALPHITEEDECALSCRIPT,
	MALPHITEESCRIPT,
	MALPHITEQDECALSCRIPT,
	MALPHITEQMODELSCRIPT,
	MALPHITEQSCRIPT,
	MALPHITERDECALSCRIPT,
	MALPHITERSCRIPT,
	MALPHITESCRIPT,
	MINIMAPUISCRIPT,
	MINIONHPBARPOSSCRIPT,
	MINIONHPRATIOSCRIPT,
	MINIONSCRIPT,
	MOBSCRIPT,
	MOUSECURSORUISCRIPT,
	MOVECURSORUISCRIPT,
	MURKWOLFMINISCRIPT,
	MURKWOLFSCRIPT,
	NEXUSSCRIPT,
	OTHERPLAYERSCRIPT,
	PLAYERSCRIPT,
	PROJECTILESCRIPT,
	RAZORBEAKMINISCRIPT,
	RAZORBEAKSCRIPT,
	REDSCRIPT,
	SCOREPANELSCRIPT,
	SKILLLEVELUISCRIPT,
	SKILLLEVELUPUISCRIPT,
	SKILLLVEFFECTUISCRIPT,
	SOUNDTESTSCRIPT,
	STRUCTURESCRIPT,
	TESTTURRETSCRIPT,
	TURRETATTACKSCRIPT,
	TURRETHPUISCRIPT,
	TURRETSCRIPT,
	UISCRIPT,
	UNITSCRIPT,
	WORLDHPSPAWNSCRIPT,
	WORLDHPUISCRIPT,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
